<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:tns="http://generic.transactis.bus.boursorama.fr/"
             xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema"
             name="SMPCardServices"
             targetNamespace="http://generic.transactis.bus.boursorama.fr/">

    <types>
        <xsd:schema attributeFormDefault="unqualified" elementFormDefault="unqualified"
                    targetNamespace="http://generic.transactis.bus.boursorama.fr/">

            <xsd:element name="notifier" type="tns:notifier"/>
            <xsd:element name="notifierResponse" type="tns:notifierResponse"/>

            <xsd:complexType name="notifier">
                <xsd:sequence>
                    <xsd:element name="messageSMPAllerXML" minOccurs="1" maxOccurs="1">
                        <xsd:complexType>
                            <xsd:sequence minOccurs="1" maxOccurs="1">
                                <xsd:any maxOccurs="1" minOccurs="1" processContents="lax"/>
                            </xsd:sequence>
                        </xsd:complexType>
                    </xsd:element>

                </xsd:sequence>
            </xsd:complexType>
            <xsd:complexType name="notifierResponse">
                <xsd:sequence>
                    <xsd:element name="messageSMPRetourXML" minOccurs="1" maxOccurs="1">
                        <xsd:complexType>
                            <xsd:sequence>
                                <xsd:any maxOccurs="1" minOccurs="1" processContents="lax"/>
                            </xsd:sequence>
                        </xsd:complexType>
                    </xsd:element>
                </xsd:sequence>
            </xsd:complexType>

        </xsd:schema>
    </types>
    <message name="notifier">
        <part element="tns:notifier" name="parameters">
        </part>
    </message>
    <message name="notifierResponse">
        <part element="tns:notifierResponse" name="parameters">
        </part>
    </message>

    <portType name="SMPEvolanFacadeDelegate">
        <operation name="notifier">
            <input message="tns:notifier"
                   wsam:Action="http://generic.transactis.bus.boursorama.fr/SMPEvolanFacadeDelegate/notifierRequest"/>
            <output message="tns:notifierResponse"
                    wsam:Action="http://generic.transactis.bus.boursoram.fr/SMPEvolanFacadeDelegate/notifierResponse"/>
        </operation>
    </portType>
    <binding name="SMPEvolanPortBinding" type="tns:SMPEvolanFacadeDelegate">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="notifier">
            <soap:operation soapAction=""/>
            <input>
                <soap:body namespace="http://generic.transactis.bus.boursorama.fr/" use="literal"/>
            </input>
            <output>
                <soap:body namespace="http://generic.transactis.bus.boursorama.fr/" use="literal"/>
            </output>
        </operation>
    </binding>
    <service name="SMPCardServices">
        <port binding="tns:SMPEvolanPortBinding" name="SMPEvolanPort">
            <soap:address location="http://localhost:8080/bus/soap/SMPCardServices"/>
        </port>
    </service>

</definitions>